export const ITEM_LIST_REQUEST='ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS='ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL='ITEM_LIST_FAIL'
export const ITEM_LIST_UPDATE='ITEM_LIST_UPDATE'

export const ITEM_ADD_REQUEST='ITEM_ADD_REQUEST'
export const ITEM_ADD_SUCCESS='ITEM_ADD_SUCCESS'
export const ITEM_ADD_FAIL='ITEM_ADD_FAIL'

export const ITEM_DELETE_REQUEST='ITEM_DELETE_REQUEST'
export const ITEM_DELETE_SUCCESS='ITEM_DELETE_SUCCESS'
export const ITEM_DELETE_FAIL='ITEM_DELETE_FAIL'

export const ITEM_PRIVATE_LIST_REQUEST='ITEM_PRIVATE_LIST_REQUEST'
export const ITEM_PRIVATE_LIST_SUCCESS='ITEM_PRIVATE_LIST_SUCCESS'
export const ITEM_PRIVATE_LIST_FAIL='ITEM_PRIVATE_LIST_FAIL'

export const ITEM_ALL_MY_LIST_REQUEST='ITEM_ALL_MY_LIST_REQUEST'
export const ITEM_ALL_MY_LIST_SUCCESS='ITEM_ALL_MY_LIST_SUCCESS'
export const ITEM_ALL_MY_LIST_FAIL='ITEM_ALL_MY_LIST_FAIL'

export const ITEM_ALL_LIST_REQUEST='ITEM_ALL_LIST_REQUEST'
export const ITEM_ALL_LIST_SUCCESS='ITEM_ALL_LIST_SUCCESS'
export const ITEM_ALL_LIST_FAIL='ITEM_ALL_LIST_FAIL'