export const GET_PUBLIC_LISTS_REQUEST ='GET_PUBLIC_LISTS_REQUEST'
export const GET_PUBLIC_LISTS_SUCCESS ='GET_PUBLIC_LISTS_SUCCESS'
export const GET_PUBLIC_LISTS_FAIL ='GET_PUBLIC_LISTS_FAIL'
export const GET_PUBLIC_LISTS_UPDATE ='GET_PUBLIC_LISTS_UPDATE'

export const GET_PRIVATE_LISTS_REQUEST ='GET_PRIVATE_LISTS_REQUEST'
export const GET_PRIVATE_LISTS_SUCCESS ='GET_PRIVATE_LISTS_SUCCESS'
export const GET_PRIVATE_LISTS_FAIL ='GET_PRIVATE_LISTS_FAIL'

export const GET_ALL_MY_LISTS_REQUEST ='GET_ALL_MY_LISTS_REQUEST'
export const GET_ALL_MY_LISTS_SUCCESS ='GET_ALL_MY_LISTS_SUCCESS'
export const GET_ALL_MY_LISTS_FAIL ='GET_ALL_MY_LISTS_FAIL'

export const GET_ALL_LISTS_REQUEST ='GET_ALL_LISTS_REQUEST'
export const GET_ALL_LISTS_SUCCESS ='GET_ALL_LISTS_SUCCESS'
export const GET_ALL_LISTS_FAIL ='GET_ALL_LISTS_FAIL'

export const ADD_LIST_REQUEST ='ADD_LIST_REQUEST'
export const ADD_LIST_SUCCESS ='ADD_LIST_SUCCESS'
export const ADD_LIST_FAIL ='ADD_LIST_FAIL'
export const ADD_LIST_RESET ='ADD_LIST_RESET' 

export const DELETE_LIST_REQUEST ='DELETE_LIST_REQUEST'
export const DELETE_LIST_SUCCESS ='DELETE_LIST_SUCCESS'
export const DELETE_LIST_FAIL ='DELETE_LIST_FAIL'

export const ADD_LIST_ITEM_REQUEST ='ADD_LIST_ITEM_REQUEST'
export const ADD_LIST_ITEM_SUCCESS ='ADD_LIST_ITEM_SUCCESS'
export const ADD_LIST_ITEM_FAIL ='ADD_LIST_ITEM_FAIL'

export const DELETE_LIST_ITEM_REQUEST ='DELETE_LIST_ITEM_REQUEST'
export const DELETE_LIST_ITEM_SUCCESS ='DELETE_LIST_ITEM_SUCCESS'
export const DELETE_LIST_ITEM_FAIL ='DELETE_LIST_ITEM_FAIL'